const Food = [
  { word: { chinese: "苹果", pinyin: "píngguǒ" } },
  { word: { chinese: "西瓜", pinyin: "xīguā" } },
  { word: { chinese: "和", pinyin: "hé" } },
  { word: { chinese: "吃", pinyin: "chī" } },
  { word: { chinese: "芒果", pinyin: "mángguǒ" } },
  { word: { chinese: "菠萝", pinyin: "bōluó" } },
  { word: { chinese: "面包", pinyin: "miànbāo" } },
  { word: { chinese: "鸡蛋", pinyin: "jīdàn" } },
  { word: { chinese: "饼干", pinyin: "bǐnggān" } },
  { word: { chinese: "水果", pinyin: "shuǐguǒ" } },
  { word: { chinese: "喜欢", pinyin: "xǐhuan" } },
  { word: { chinese: "喝", pinyin: "hē" } },
  { word: { chinese: "茶", pinyin: "chá" } },
  { word: { chinese: "咖啡", pinyin: "kāfēi" } },
  { word: { chinese: "果汁", pinyin: "guǒzhī" } },
  { word: { chinese: "水", pinyin: "shuǐ" } },
  { word: { chinese: "想", pinyin: "xiǎng" } },
  { word: { chinese: "买", pinyin: "mǎi" } },
  { word: { chinese: "牛奶", pinyin: "niúnǎi" } },
  { word: { chinese: "啤酒", pinyin: "píjiǔ" } },
  { word: { chinese: "可乐", pinyin: "kělè" } },
];

export default Food;
