export const Titles = [
  { english: "Hello", chinese: "你好" },
  { english: "Food", chinese: "食物" },
  { english: "School1", chinese: "学校" },
  { english: "Money", chinese: "钱" },
  { english: "Dates", chinese: "日期" },
  { english: "Locations", chinese: "地点" },
  { english: "Personal Information", chinese: "我" },
  { english: "Time", chinese: "时间" },
  { english: "Hometown", chinese: "家乡" },
  { english: "Taste", chinese: "" },
  { english: "Restaurants 1", chinese: "" },
  { english: "Daily Schedule", chinese: "" },
  { english: "Leisure", chinese: "" },
  { english: "Appearance", chinese: "" },
  { english: "Clothes", chinese: "" },
  { english: "Colors", chinese: "" },
  { english: "Shopping", chinese: "" },
  { english: "Sports", chinese: "" },
  { english: "Spare Time", chinese: "" },
  { english: "Transport", chinese: "" },
  { english: "Directions", chinese: "" },
  { english: "Rooms", chinese: "" },
  { english: "Weather", chinese: "" },
  { english: "Phone-Calls", chinese: "" },
  { english: "Communications", chinese: "" },
  { english: "Sweets", chinese: "" },
  { english: "Pets", chinese: "" },
  { english: "Suggestions", chinese: "" },
  { english: "Health", chinese: "" },
  { english: "Ordering Food", chinese: "" },
  { english: "Restaurants 2", chinese: "" },
  { english: "Helping Out", chinese: "" },
  { english: "Bargaining", chinese: "" },
  { english: "Learning Chinese 2", chinese: "" },
  { english: "School", chinese: "" },
  { english: "Dating", chinese: "" },
  { english: "Feelings", chinese: "" },
  { english: "Family 2", chinese: "" },
  { english: "Career", chinese: "" },
  { english: "Traveling 1", chinese: "" },
  { english: "Going Abroad", chinese: "" },
  { english: "Catching a Flight", chinese: "" },
  { english: "Traveling 2", chinese: "" },
  { english: "Renting", chinese: "" },
  { english: "Daily Life", chinese: "" },
  { english: "Habits", chinese: "" },
  { english: "Mistakes", chinese: "" },
  { english: "Interviews", chinese: "" },
  { english: "Work", chinese: "" },
  { english: "Bad Luck", chinese: "" },
  { english: "Greetings", chinese: "" },
  { english: "Online Shopping", chinese: "" },
  { english: "Office Work", chinese: "" },
  { english: "Sports Competitions", chinese: "" },
  { english: "Gossip", chinese: "" },
  { english: "Hiking", chinese: "" },
  { english: "Comparing", chinese: "" },
  { english: "Arguments", chinese: "" },
  { english: "Personality", chinese: "" },
  { english: "Praise", chinese: "" },
  { english: "Weight Loss", chinese: "" },
  { english: "Housework", chinese: "" },
  { english: "Movies", chinese: "" },
  { english: "Apologizing", chinese: "" },
  { english: "Shocked", chinese: "" },
  { english: "China 1", chinese: "" },
  { english: "China 2", chinese: "" },
  { english: "Nature", chinese: "" },
  { english: "Environment", chinese: "" },
];
