import { useState } from "react";
import Head from "next/head";
import Patterns from "../components/Patterns";
import Words from "~/components/spelling/Words";
import Welcome from "../components/infoPages/Welcome";
import SideNav from "~/components/nav/SideNav";
import TopNav from "~/components/nav/TopNav";
import Overview from "~/components/Overview";
import AlphabetC from "~/components/Pronunciation";
import { register } from "~/wordBank";
import { Box, createTheme, CssBaseline, ThemeProvider } from "@mui/material";
import { atom } from "jotai";

export const sideNavState = atom(false);

const darkTheme = createTheme({
  palette: {
    mode: "dark",
    background: {
      default: "#1a1a1a",
      paper: "#1a1a1a",
    },
  },
  typography: {
    fontFamily: "Tahoma, Helvetica, sans-serif;",
  },
});

export default function Home() {
  const [deck, setDeck] = useState();
  const [deckName, setDeckName] = useState("");
  const [tab, setTab] = useState<string | undefined>(undefined);
  const [initialRender, setInitialRender] = useState(true);
  const [volumne, setVolumne] = useState<number>(1);

  const switchDeck = (text: string) => {
    setInitialRender(false);
    setDeck(undefined);
    setTimeout(() => {
      const name = text.replaceAll(" ", "_");
      setDeck(register[name]);
      setDeckName(text);
    }, 100);
  };

  const backToHome = () => {
    setDeck(undefined);
    setInitialRender(true);
  };

  const getPage = () => {
    if (deckName === "Alphabet") {
      return <AlphabetC words={deck} />;
    } else {
      if (tab === "game") {
        return <Patterns />;
      } else if (tab === "spelling") {
        return (
          <Words
            deck={deck}
            deckName={deckName}
            setVolumne={setVolumne}
            volumne={volumne}
          />
        );
      } else {
        return <Overview deck={deck} />;
      }
    }
  };

  return (
    <div>
      <Head>
        <title>TypeIt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={darkTheme}>
        <Box sx={{ maxHeight: "100vh", maxWidth: "100vw" }}>
          <TopNav backToHome={backToHome} deck={deck} setTab={setTab} />
          <SideNav switchDeck={switchDeck} />
          <Box
            sx={{
              width: "100%",
              height: "calc(100vh - 50px)",
              // border: "solid white 1px",
              position: "absolute",
              bottom: 0,
              right: 0,
            }}
          >
            {deck && getPage()}
            {initialRender && <Welcome />}
          </Box>
          <CssBaseline />
        </Box>
      </ThemeProvider>
    </div>
  );
}
