import Head from "next/head";
import styles from "../styles/Home.module.css";
import Words from "~/components/Words";
import Hello from "../components/wordBank/Hello";
import Food from "../components/wordBank/Food";
import Money from "../components/wordBank/Money";
import { useState } from "react";
import { Box, createTheme, CssBaseline, ThemeProvider } from "@mui/material";
import SideNav from "~/components/SideNav";
import TopNav from "~/components/TopNav";
import Welcome from "../components/Welcome";
import School1 from "../components/wordBank/School1";

type registerType = {
  [key: string]: any;
};

const darkTheme = createTheme({
  palette: {
    mode: "dark",
    background: {
      default: "black",
      paper: "black",
    },
  },
});

export default function Home() {
  const [deck, setDeck] = useState();
  const [deckName, setDeckName] = useState("");
  const [initialRender, setInitialRender] = useState(true);
  const register: registerType = {
    Hello,
    Food,
    School1,
    Money,
  };

  const switchDeck = (text: string) => {
    setInitialRender(false);
    setDeck(undefined);
    setTimeout(() => {
      setDeck(register[text]);
      setDeckName(text);
    }, 100);
  };

  const backToHome = () => {
    setDeck(undefined);
    setInitialRender(true);
  };

  return (
    <div>
      <Head>
        <title>TypeIt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={darkTheme}>
        <Box
          display="flex"
          flexDirection="column"
          sx={{ height: "100vh", width: "100vw" }}
        >
          <TopNav backToHome={backToHome} />
          <Box
            display="flex"
            flexDirection="row"
            sx={{ height: "100%", width: "100%" }}
          >
            <SideNav switchDeck={switchDeck} />
            {deck ? <Words deck={deck} deckName={deckName} /> : null}
            {initialRender && <Welcome />}
          </Box>
          <CssBaseline />
        </Box>
      </ThemeProvider>
    </div>
  );
}
