export const Weight_Loss = [
  { word: { chinese: "尽管", pinyin: "jǐnguǎn" } },
  { word: { chinese: "减肥", pinyin: "jiǎnféi" } },
  { word: { chinese: "锻炼", pinyin: "duànliàn" } },
  { word: { chinese: "坚持", pinyin: "jiānchí" } },
  { word: { chinese: "辛苦", pinyin: "xīnkǔ" } },
  { word: { chinese: "身材", pinyin: "shēncái" } },
  { word: { chinese: "快餐", pinyin: "kuàicān" } },
  { word: { chinese: "蔬菜", pinyin: "shūcài" } },
  { word: { chinese: "牛肉", pinyin: "niúròu" } },
  { word: { chinese: "鸡肉", pinyin: "jīròu" } },
  { word: { chinese: "否则", pinyin: "fǒuzé" } },
  { word: { chinese: "节食", pinyin: "jiéshí" } },
  { word: { chinese: "难受", pinyin: "nánshòu" } },
  { word: { chinese: "身体", pinyin: "shēntǐ" } },
  { word: { chinese: "皮肤", pinyin: "pífū" } },
];
